version: '3.5'
services:
  prometheus:
    image: prometheus:latest
    container_name: prometheus
    volumes:
      -./prometheus.yml:/etc/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana:latest
    container_name: grafana
    ports:
      - "9090:9090"
  node_exporter:
     image: linuxkit/node_exporter:latest
     container_name: node
     ports:
      -"9100:9100"